-- MySQL Script generated by MySQL Workbench
-- Fri Sep 17 19:50:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `tipoUsuario` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `tipoIdentificacion` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `estadoCivil` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `eps` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesores` (
  `idProfesorescol` INT NOT NULL AUTO_INCREMENT,
  `idUsuariosProfesores` INT NOT NULL,
  `tipoContrato` VARCHAR(45) NULL,
  `salario` DOUBLE NULL,
  `titulo` VARCHAR(45) NULL,
  `escalafon` VARCHAR(45) NULL,
  `fechaIngreso` DATE NULL,
  `fechaEgreso` DATE NULL,
  PRIMARY KEY (`idProfesorescol`),
  UNIQUE INDEX `idProfesorescol_UNIQUE` (`idProfesorescol` ASC) VISIBLE,
  UNIQUE INDEX `idUsuariosProfesores_UNIQUE` (`idUsuariosProfesores` ASC) VISIBLE,
  CONSTRAINT `UsuarioProfesores`
    FOREIGN KEY (`idUsuariosProfesores`)
    REFERENCES `mydb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grados` (
  `idGrados` INT NOT NULL AUTO_INCREMENT,
  `nombreGrado` VARCHAR(45) NOT NULL,
  `salon` VARCHAR(45) NOT NULL,
  `idProfesoresGrupos` INT NULL,
  `idEstudianteGrupo` INT NULL,
  PRIMARY KEY (`idGrados`),
  UNIQUE INDEX `idGrados_UNIQUE` (`idGrados` ASC) VISIBLE,
  UNIQUE INDEX `GradoUnico` (`nombreGrado` ASC, `salon` ASC) VISIBLE,
  INDEX `DirectorGrupos_idx` (`idProfesoresGrupos` ASC) VISIBLE,
  INDEX `RepresentanteAlumnos_idx` (`idEstudianteGrupo` ASC) VISIBLE,
  UNIQUE INDEX `idEstudianteGrupo_UNIQUE` (`idEstudianteGrupo` ASC) VISIBLE,
  CONSTRAINT `DirectorGrupos`
    FOREIGN KEY (`idProfesoresGrupos`)
    REFERENCES `mydb`.`Profesores` (`idProfesorescol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RepresentanteAlumnos`
    FOREIGN KEY (`idEstudianteGrupo`)
    REFERENCES `mydb`.`Alumnos` (`idAlumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumnos` (
  `idAlumnos` INT NOT NULL AUTO_INCREMENT,
  `idUsuariosAlumnos` INT NOT NULL,
  `idGradosEstudiantes` INT NULL,
  `estrato` VARCHAR(45) NULL,
  PRIMARY KEY (`idAlumnos`),
  INDEX `UsuariosEstudiantes_idx` (`idUsuariosAlumnos` ASC) VISIBLE,
  INDEX `GruposEstudiantes_idx` (`idGradosEstudiantes` ASC) VISIBLE,
  CONSTRAINT `UsuariosEstudiantes`
    FOREIGN KEY (`idUsuariosAlumnos`)
    REFERENCES `mydb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `GruposEstudiantes`
    FOREIGN KEY (`idGradosEstudiantes`)
    REFERENCES `mydb`.`Grados` (`idGrados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
