-- MySQL Script generated by MySQL Workbench
-- Tue Oct  5 20:14:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `tipoUsuario` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `tipoIdentificacion` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `estadoCivil` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `eps` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesores` (
  `idProfesorescol` INT NOT NULL AUTO_INCREMENT,
  `idUsuariosProfesores` INT NOT NULL,
  `tipoContrato` VARCHAR(45) NULL,
  `salario` DOUBLE NULL,
  `titulo` VARCHAR(45) NULL,
  `escalafon` VARCHAR(45) NULL,
  `fechaIngreso` DATE NULL,
  `fechaEgreso` DATE NULL,
  PRIMARY KEY (`idProfesorescol`),
  UNIQUE INDEX `idProfesorescol_UNIQUE` (`idProfesorescol` ASC) VISIBLE,
  CONSTRAINT `UsuarioProfesores`
    FOREIGN KEY (`idUsuariosProfesores`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SedeEducativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SedeEducativa` (
  `idSedeEducativa` INT NOT NULL AUTO_INCREMENT,
  `sedeEducativacol` VARCHAR(45) NOT NULL,
  `nid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSedeEducativa`),
  UNIQUE INDEX `idSedeEducativa_UNIQUE` (`idSedeEducativa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante` (
  `idEstudiante` INT NOT NULL AUTO_INCREMENT,
  `idUsuariosEstudiante` INT NOT NULL,
  `idSedeEducativaEstudiante` INT NOT NULL,
  `estrato` VARCHAR(45) NULL,
  `nombresAcudiente` VARCHAR(45) NULL,
  `apellidosAcudiente` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstudiante`),
  INDEX `UsuariosEstudiantes_idx` (`idUsuariosEstudiante` ASC) INVISIBLE,
  UNIQUE INDEX `idEstudiante_UNIQUE` (`idEstudiante` ASC) VISIBLE,
  UNIQUE INDEX `idUsuariosEstudiante_UNIQUE` (`idUsuariosEstudiante` ASC) VISIBLE,
  UNIQUE INDEX `idSedeEducativaEstudiante_UNIQUE` (`idSedeEducativaEstudiante` ASC) VISIBLE,
  CONSTRAINT `UsuariosEstudiantes`
    FOREIGN KEY (`idUsuariosEstudiante`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AlumnoSedeEducativa`
    FOREIGN KEY (`idSedeEducativaEstudiante`)
    REFERENCES `mydb`.`SedeEducativa` (`idSedeEducativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matricula` (
  `idMatricula` INT NOT NULL AUTO_INCREMENT,
  `idEstudiante` INT NOT NULL,
  `year` VARCHAR(4) NOT NULL,
  `periodo` VARCHAR(45) NOT NULL,
  `fechaMatricula` DATE NOT NULL,
  `grado` VARCHAR(20) NULL,
  PRIMARY KEY (`idMatricula`),
  INDEX `idEstudiante` (`idEstudiante` ASC) VISIBLE,
  UNIQUE INDEX `idMatricula_UNIQUE` (`idMatricula` ASC) VISIBLE,
  CONSTRAINT `EstudianteMatricula`
    FOREIGN KEY (`idEstudiante`)
    REFERENCES `mydb`.`Estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
