-- MySQL Script generated by MySQL Workbench
-- Fri Sep 10 18:30:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TablasSimatSql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TablasSimatSql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TablasSimatSql` DEFAULT CHARACTER SET utf8 ;
USE `TablasSimatSql` ;

-- -----------------------------------------------------
-- Table `TablasSimatSql`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TablasSimatSql`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `tipoIdentificacion` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `estadoCivil` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `eps` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TablasSimatSql`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TablasSimatSql`.`Profesores` (
  `idProfesorescol` INT NOT NULL AUTO_INCREMENT,
  `idUsuariosProfesores` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfesorescol`),
  UNIQUE INDEX `idProfesorescol_UNIQUE` (`idProfesorescol` ASC) VISIBLE,
  UNIQUE INDEX `idUsuariosProfesores_UNIQUE` (`idUsuariosProfesores` ASC) VISIBLE,
  CONSTRAINT `UsuarioProfesores`
    FOREIGN KEY (`idUsuariosProfesores`)
    REFERENCES `TablasSimatSql`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TablasSimatSql`.`SedeEducativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TablasSimatSql`.`SedeEducativa` (
  `idSedeEducativa` INT NOT NULL AUTO_INCREMENT,
  `sedeEducativacol` VARCHAR(45) NOT NULL,
  `nid` VARCHAR(45) NOT NULL,
  `jornada` VARCHAR(45) NULL,
  PRIMARY KEY (`idSedeEducativa`),
  UNIQUE INDEX `idSedeEducativa_UNIQUE` (`idSedeEducativa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TablasSimatSql`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TablasSimatSql`.`Estudiante` (
  `idAlumnos` INT NOT NULL AUTO_INCREMENT,
  `idUsuariosAlumnos` INT NOT NULL,
  `idSede` INT NOT NULL,
  `estrato` VARCHAR(45) NULL,
  `idAcudiente` INT NOT NULL,
  PRIMARY KEY (`idAlumnos`),
  INDEX `UsuariosEstudiantes_idx` (`idUsuariosAlumnos` ASC) INVISIBLE,
  INDEX `AcudienteEstudiante_idx` (`idAcudiente` ASC) VISIBLE,
  CONSTRAINT `UsuariosEstudiantes`
    FOREIGN KEY (`idUsuariosAlumnos`)
    REFERENCES `TablasSimatSql`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AlumnoSedeEducativa`
    FOREIGN KEY (`idSede`)
    REFERENCES `TablasSimatSql`.`SedeEducativa` (`idSedeEducativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AcudienteEstudiante`
    FOREIGN KEY (`idAcudiente`)
    REFERENCES `TablasSimatSql`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TablasSimatSql`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TablasSimatSql`.`Matricula` (
  `idMatricula` INT NOT NULL AUTO_INCREMENT,
  `idEstudiante` INT NOT NULL,
  `year` VARCHAR(4) NOT NULL,
  `periodo` VARCHAR(45) NOT NULL,
  `fechaMatricula` DATE NOT NULL,
  `grado` VARCHAR(20) NULL,
  PRIMARY KEY (`idMatricula`),
  INDEX `idAlumnos` (`idEstudiante` ASC) VISIBLE,
  UNIQUE INDEX `idMatricula_UNIQUE` (`idMatricula` ASC) VISIBLE,
  CONSTRAINT `AlumnoMatricula`
    FOREIGN KEY (`idEstudiante`)
    REFERENCES `TablasSimatSql`.`Estudiante` (`idAlumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
